# Imports

In [1]:
import pandas as pd
import numpy as np
from joblib import Parallel, delayed
from tqdm import tqdm
import plotly.express as px

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 300)

# Load

In [3]:
file_path = 'E:/ML/datasets/mahjong/data/2019/block_5000.parquet'

In [4]:
states = pd.read_parquet(file_path)

In [5]:
states.columns = states.columns.map(
    str
)

## Trim unneeded columns to save on space

In [6]:
dora_columns = []
for i in range(34,68):
    dora_columns = dora_columns + [str(i)]

In [7]:
hand_columns = []
for i in range(68,102):
    hand_columns = hand_columns + [str(i)]

In [8]:
states['group_id'] = states['511'].astype(str) + states['32'].astype(str) + states['2'].astype(str)

In [9]:
columns_of_interest = ['group_id'] + ['0', '1','2','10','11','12','13'] + dora_columns + hand_columns + ['510']

In [10]:
states = states[columns_of_interest]

In [11]:
states[states.columns[1:]] = states[states.columns[1:]].astype(int)

In [12]:
states.shape

(2412918, 77)

## Remove multi-dora states

In [13]:
states_dora_sum = states.loc[:, dora_columns].sum(axis=1)

In [14]:
states = states.loc[states_dora_sum == 1]

In [15]:
def is_chiitoi_tenpai(state):
    hand = state[hand_columns]
    num_pairs = len(hand.drop(hand[hand.isin([0,1])].index))
    if num_pairs == 6:
        return True
    return False

In [16]:
chiitois = Parallel(n_jobs=-1)(
    delayed(lambda i: is_chiitoi_tenpai(i))(i)
    for _, i in tqdm(states.iterrows())
)

2340837it [03:10, 12269.37it/s]

In [17]:
pd.Series(chiitois).value_counts()

False    2332436
True        8401
Name: count, dtype: int64

In [18]:
states['is_chiitoi'] = 0
states.loc[chiitois,'is_chiitoi'] = 1

# Generate Hand Groups

In [19]:
hand_groups = states.groupby('group_id')

# Determine chiitoi tenpais in hand groups

In [20]:
def is_chiitoi_tenpai(hand):
    num_pairs = len(hand.drop(hand[hand.isin([0,1])].index))
    if num_pairs == 6:
        return True
    return False

In [21]:
def generate_is_chiitoi_dict(hand_group):
    hand_group = hand_group.reset_index(drop=True)
    for i, r in hand_group.iterrows():
        if is_chiitoi_tenpai(r[hand_columns]):
            hand_len = i
            is_chiitoi = 1
            return {'length': hand_len, 'is_chiitoi': is_chiitoi}
            
    
    return {'length': hand_group.shape[0], 'is_chiitoi': 0}

In [22]:
len_chiitois = Parallel(n_jobs=-1)(
    delayed(lambda i: generate_is_chiitoi_dict(i))(i)
    for _, i in tqdm(hand_groups.__iter__())
)

210550it [04:05, 857.66it/s]

In [23]:
len_chi_df = pd.DataFrame(len_chiitois)

In [24]:
len_chi_df.loc[len_chi_df['is_chiitoi'] == 1]

        length  is_chiitoi
9            9           1
12           6           1
70          13           1
175          5           1
229         11           1
...        ...         ...
209822       9           1
209992       8           1
210013       9           1
210063       7           1
210318       6           1

[3601 rows x 2 columns]

# Determine discard count distribution for chiitoi tenpai hands

In [25]:
total_chiitoi_hands = len_chi_df.loc[len_chi_df['is_chiitoi']==1]['length'].value_counts().sum()
chiitoi_value_counts = len_chi_df.loc[len_chi_df['is_chiitoi']==1]['length'].value_counts()

In [26]:
chiitoi_dist = chiitoi_value_counts/total_chiitoi_hands

# Process hand groups

In [27]:
def id_to_tile(id):
    return id %34

In [53]:
def player_round_to_discards(round_df, stop = None):
    round_df = round_df.reset_index(drop=True)
    if stop:
        round_df = round_df.iloc[:stop]
    else:
        chiitoi_hand = round_df.loc[round_df['is_chiitoi']==1]
        if chiitoi_hand.shape[0] != 0:
            round_df = round_df.iloc[:chiitoi_hand.index[0]+1]
        
    wind = [round_df['0'].iloc[0]]

    seat = [round_df['2'].iloc[0]]
    
    dealer = [int((round_df['1'].iloc[0] - round_df['2'].iloc[0]) == 0)]
    
    last_riichi = round_df.iloc[-1][['10','11','12','13']].reset_index(drop=True)

    is_riichi = [last_riichi[round_df['2'].iloc[0]]]
    
    dora_series = round_df[dora_columns].iloc[0]
    dora = [id_to_tile(int(dora_series.loc[dora_series==1].index[0]))]

    discards = round_df['510'].to_list()

    """
    Round Wind Space: 34-37 (+34)
    Seat Wind Space 38-41 (+38)
    is riichi space 44-45 (+44)
    dora space (46-79) (+46)
    discard_space 0-33
    """

    wind = [w + 34 for w in wind]
    seat = [s + 38 for s in seat]
    is_riichi = [i + 44 for i in is_riichi]
    dora = [d + 46 for d in dora]

    return wind + seat + is_riichi + dora + discards

In [54]:
def handle_hand_group(hand_group, dist_chiitois):
    
    # first, determine if this hand group contains a chiitoi tenpai.
    has_chiitoi_tenpai = hand_group['is_chiitoi'].sum() > 0

    if has_chiitoi_tenpai:
        return player_round_to_discards(hand_group), 1
    else:
        stop_val = np.random.choice(dist_chiitois.index, p=dist_chiitois)
        return player_round_to_discards(hand_group, stop=stop_val), 0

In [55]:
def generate_hand_group_dict(hand_group, dist_chiitois):
    seq, is_chiitoi = handle_hand_group(hand_group, dist_chiitois)

    return {'group_id': hand_group['group_id'].iloc[0], 'seq': seq, 'is_chiitoi': is_chiitoi}

In [ ]:
full_hands = Parallel(n_jobs=-1)(
    delayed(lambda i: generate_hand_group_dict(i, chiitoi_dist))(i)
    for _, i in tqdm(hand_groups.__iter__())
)

# Export

In [57]:
full_hands_df = pd.DataFrame(full_hands)

In [58]:
full_hands_df

,group_id,seq,is_chiitoi
0,0009fd0000,"[34, 38, 44, 66, 18, 30, 29, 9, 18, 33, 25, 31...",0
1,0009fd0001,"[34, 39, 44, 66, 30, 33, 28, 1, 5, 10, 2, 10]",0
2,0009fd0002,"[34, 40, 44, 66, 9, 30, 29, 10, 12, 5, 8, 8, 2...",0
3,0009fd0003,"[34, 41, 44, 66, 30, 29, 17, 28, 25, 19]",0
4,0009fd0010,"[34, 38, 44, 51, 17, 8, 28, 17, 29, 33, 32, 31...",0
...,...,...,...
210545,ffe9d48e83,"[35, 41, 44, 61, 33]",0
210546,ffe9d48e90,"[35, 38, 44, 62, 30, 18, 32, 27, 8, 29, 18, 33...",0
210547,ffe9d48e91,"[35, 39, 44, 62, 18, 27, 26, 33, 0, 21, 23, 30...",0
210548,ffe9d48e92,"[35, 40, 44, 62, 29, 32, 27]",0
210549,ffe9d48e93,"[35, 41, 44, 62, 8, 9, 32, 33, 8, 31, 28]",0

In [59]:
full_hands_df.to_csv('full_hands_df_3_15_2025.csv', index=False)