# Imports

In [11]:
import pandas as pd
import numpy as np
from joblib import Parallel, delayed
from tqdm import tqdm
import plotly.express as px

In [12]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 300)

# Load

In [13]:
file_path = 'E:/ML/datasets/mahjong/data/2019/block_5000.parquet'

In [14]:
states = pd.read_parquet(file_path)

In [15]:
states.columns = states.columns.map(
    str
)

In [16]:
states.shape

(2412918, 512)

In [17]:
states.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511
0,0,0,0,0,0,69,25,25,25,25,0,0,0,0,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,0,-126,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,2,0,0,0,1,0,1,0,1,0,1,0,0,1,0,0,0,1,0,0,1,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,28,009379d9
1,0,0,1,0,0,68,25,25,25,25,0,0,0,0,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,0,-124,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,1,0,0,1,0,0,0,1,1,1,0,0,0,0,1,0,1,0,3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,28,009379d9
2,0,0,2,0,0,67,25,25,25,25,0,0,0,0,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,0,-122,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,2,2,0,0,0,0,0,1,1,0,0,0,1,0,1,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,25,009379d9
3,0,0,3,0,0,66,25,25,25,25,0,0,0,0,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,0,-120,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,2,0,0,0,0,0,1,2,0,0,1,0,0,1,0,0,0,0,1,1,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,28,009379d9
4,0,0,0,0,0,65,25,25,25,25,0,0,0,0,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,-128,0,-118,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,2,0,0,1,1,0,1,0,1,0,1,0,0,1,0,0,0,0,0,0,1,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,31,009379d9

## Trim unneeded columns to save on space

In [18]:
dora_columns = []
for i in range(34,68):
    dora_columns = dora_columns + [str(i)]

In [19]:
hand_columns = []
for i in range(68,102):
    hand_columns = hand_columns + [str(i)]

In [20]:
states['group_id'] = states['511'].astype(str) + states['32'].astype(str) + states['2'].astype(str)

In [21]:
columns_of_interest = ['group_id'] + ['0', '1','2','10','11','12','13'] + dora_columns + hand_columns + ['510']

In [22]:
states = states[columns_of_interest]

In [23]:
states[states.columns[1:]] = states[states.columns[1:]].astype(int)

In [24]:
states.shape

(2412918, 77)

## Remove multi-dora states

In [25]:
states_dora_sum = states.loc[:, dora_columns].sum(axis=1)

In [26]:
states = states.loc[states_dora_sum == 1]

## Identify Chiitoi states

In [27]:
def is_chiitoi_tenpai(state):
    hand = state[hand_columns]
    num_pairs = len(hand.drop(hand[hand.isin([0,1])].index))
    if num_pairs == 6:
        return True
    return False

In [28]:
chiitois = Parallel(n_jobs=-1)(
    delayed(lambda i: is_chiitoi_tenpai(i))(i)
    for _, i in tqdm(states.iterrows())
)

2340837it [03:19, 11734.26it/s]

In [29]:
pd.Series(chiitois).value_counts()

False    2332436
True        8401
Name: count, dtype: int64

In [30]:
states['is_chiitoi'] = 0
states.loc[chiitois,'is_chiitoi'] = 1

# Generate Hand Groups

In [31]:
hand_groups = states.groupby('group_id')

# Determine chiitoi tenpais in hand groups

In [20]:
def is_chiitoi_tenpai(hand):
    num_pairs = len(hand.drop(hand[hand.isin([0,1])].index))
    if num_pairs == 6:
        return True
    return False

In [21]:
def generate_is_chiitoi_dict(hand_group):
    hand_group = hand_group.reset_index(drop=True)
    for i, r in hand_group.iterrows():
        if is_chiitoi_tenpai(r[hand_columns]):
            hand_len = i
            is_chiitoi = 1
            return {'length': hand_len, 'is_chiitoi': is_chiitoi}
            
    
    return {'length': hand_group.shape[0], 'is_chiitoi': 0}

In [22]:
len_chiitois = Parallel(n_jobs=-1)(
    delayed(lambda i: generate_is_chiitoi_dict(i))(i)
    for _, i in tqdm(hand_groups.__iter__())
)

210550it [04:05, 857.66it/s]

In [23]:
len_chi_df = pd.DataFrame(len_chiitois)

In [24]:
len_chi_df.loc[len_chi_df['is_chiitoi'] == 1]

        length  is_chiitoi
9            9           1
12           6           1
70          13           1
175          5           1
229         11           1
...        ...         ...
209822       9           1
209992       8           1
210013       9           1
210063       7           1
210318       6           1

[3601 rows x 2 columns]

# Determine discard count distribution for chiitoi tenpai hands

In [25]:
total_chiitoi_hands = len_chi_df.loc[len_chi_df['is_chiitoi']==1]['length'].value_counts().sum()
chiitoi_value_counts = len_chi_df.loc[len_chi_df['is_chiitoi']==1]['length'].value_counts()

In [26]:
chiitoi_dist = chiitoi_value_counts/total_chiitoi_hands

# Process hand groups

In [27]:
def id_to_tile(id):
    return id %34

In [53]:
def player_round_to_discards(round_df, stop = None):
    round_df = round_df.reset_index(drop=True)
    if stop:
        round_df = round_df.iloc[:stop]
    else:
        chiitoi_hand = round_df.loc[round_df['is_chiitoi']==1]
        if chiitoi_hand.shape[0] != 0:
            round_df = round_df.iloc[:chiitoi_hand.index[0]+1]
        
    wind = [round_df['0'].iloc[0]]

    seat = [round_df['2'].iloc[0]]
    
    dealer = [int((round_df['1'].iloc[0] - round_df['2'].iloc[0]) == 0)]
    
    last_riichi = round_df.iloc[-1][['10','11','12','13']].reset_index(drop=True)

    is_riichi = [last_riichi[round_df['2'].iloc[0]]]
    
    dora_series = round_df[dora_columns].iloc[0]
    dora = [id_to_tile(int(dora_series.loc[dora_series==1].index[0]))]

    discards = round_df['510'].to_list()

    """
    Round Wind Space: 34-37 (+34)
    Seat Wind Space 38-41 (+38)
    is riichi space 44-45 (+44)
    dora space (46-79) (+46)
    discard_space 0-33
    """

    wind = [w + 34 for w in wind]
    seat = [s + 38 for s in seat]
    is_riichi = [i + 44 for i in is_riichi]
    dora = [d + 46 for d in dora]

    return wind + seat + is_riichi + dora + discards

In [54]:
def handle_hand_group(hand_group, dist_chiitois):
    
    # first, determine if this hand group contains a chiitoi tenpai.
    has_chiitoi_tenpai = hand_group['is_chiitoi'].sum() > 0

    if has_chiitoi_tenpai:
        return player_round_to_discards(hand_group), 1
    else:
        stop_val = np.random.choice(dist_chiitois.index, p=dist_chiitois)
        return player_round_to_discards(hand_group, stop=stop_val), 0

In [55]:
def generate_hand_group_dict(hand_group, dist_chiitois):
    seq, is_chiitoi = handle_hand_group(hand_group, dist_chiitois)

    return {'group_id': hand_group['group_id'].iloc[0], 'seq': seq, 'is_chiitoi': is_chiitoi}

In [ ]:
full_hands = Parallel(n_jobs=-1)(
    delayed(lambda i: generate_hand_group_dict(i, chiitoi_dist))(i)
    for _, i in tqdm(hand_groups.__iter__())
)

# Export

In [57]:
full_hands_df = pd.DataFrame(full_hands)

In [33]:
full_hands_df

NameError: name 'full_hands_df' is not defined

In [59]:
full_hands_df.to_csv('full_hands_df_3_15_2025.csv', index=False)

In [43]:
full_hands_df = pd.read_csv('full_hands_df_3_15_2025.csv')

In [45]:
full_hands_df['is_chiitoi'].value_counts()

is_chiitoi
0    206949
1      3601
Name: count, dtype: int64