In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('grad_frame_2.csv')

In [4]:
df.head(20)

    orig_index  token_id  attribution_score  label  prediction_prob
0       130859        35           0.115245    0.0         0.009886
1       130859        39           0.076365    0.0         0.009886
2       130859        44          -0.140192    0.0         0.009886
3       130859        55           0.146613    0.0         0.009886
4       130859        28          -0.124811    0.0         0.009886
5       130859        17          -0.047729    0.0         0.009886
6       130859        29          -0.150526    0.0         0.009886
7       130859        14           0.225312    0.0         0.009886
8        44358        35           0.138316    0.0         0.012354
9        44358        38           0.081746    0.0         0.012354
10       44358        44          -0.149380    0.0         0.012354
11       44358        61           0.010840    0.0         0.012354
12       44358        32          -0.047406    0.0         0.012354
13       44358        17          -0.044387    0.0         0.012354
14       44358         4           0.289694    0.0         0.012354
15       44358        20           0.280699    0.0         0.012354
16        2051        34          -0.110592    0.0         0.060517
17        2051        41           0.171759    0.0         0.060517
18        2051        44          -0.183577    0.0         0.060517
19        2051        47          -0.047607    0.0         0.060517

In [5]:
df['label'].value_counts()

label
0.0    470648
1.0     10139
Name: count, dtype: int64

In [17]:
df_ch_only = df.loc[df['label']==1]

In [18]:
df_ch_only

        orig_index  token_id  attribution_score  label  prediction_prob
1449        136742        34          -0.115970    1.0         0.010531
1450        136742        39           0.170014    1.0         0.010531
1451        136742        44          -0.134839    1.0         0.010531
1452        136742        77           0.050722    1.0         0.010531
1453        136742        33          -0.176364    1.0         0.010531
...            ...       ...                ...    ...              ...
478920       34949        13           0.046510    1.0         0.037506
478921       34949         5           0.370585    1.0         0.037506
478922       34949        29          -0.311250    1.0         0.037506
478923       34949        23          -0.031784    1.0         0.037506
478924       34949        31          -0.016853    1.0         0.037506

[10139 rows x 5 columns]

In [19]:
pred_95 = df_ch_only['prediction_prob'].quantile(0.9)

In [20]:
sort_95 = df_ch_only.loc[df_ch_only['prediction_prob']>pred_95].sort_values('prediction_prob', ascending=False)

In [21]:
top_25 = sort_95[['orig_index','label','prediction_prob']].drop_duplicates()[:30]['orig_index']

In [22]:
sort_95[['orig_index','label','prediction_prob']].drop_duplicates()[:30]

        orig_index  label  prediction_prob
415895      196822    1.0         0.353081
453473      178489    1.0         0.322500
446168       30999    1.0         0.310133
312571      123130    1.0         0.296784
120534       87929    1.0         0.296672
177550         868    1.0         0.290375
239965      137871    1.0         0.263918
162811       53527    1.0         0.260562
63496        53887    1.0         0.255195
419267      183239    1.0         0.251368
306742       28782    1.0         0.250584
218234       16758    1.0         0.241535
439670      188301    1.0         0.239883
474427      143301    1.0         0.218934
347777      150504    1.0         0.218662
352942       81900    1.0         0.208297
469899       82771    1.0         0.206864
380647      105366    1.0         0.206140
365718       97128    1.0         0.194729
128973      147181    1.0         0.193884
10488        48299    1.0         0.190917
257878       25127    1.0         0.190124
71423       142408    1.0         0.186508
272890      195246    1.0         0.176545
252114       22714    1.0         0.175473
185805      132598    1.0         0.174805
451088      165568    1.0         0.169723
104580      191050    1.0         0.165743
343390      116879    1.0         0.164151
20391        66892    1.0         0.156087

# Discards

In [11]:
mahjong_tiles = [
    # Manzu (Characters)
    "1m", "2m", "3m", "4m", "5m", "6m", "7m", "8m", "9m",
    
    # Souzu (Bamboos)
    "1s", "2s", "3s", "4s", "5s", "6s", "7s", "8s", "9s",
    
    # Pinzu (Circles)
    "1p", "2p", "3p", "4p", "5p", "6p", "7p", "8p", "9p",
    
    # Winds
    "East", "South", "West", "North",
    
    # Dragons (Colors)
    "White", "Green", "Red"
]

In [12]:
wind_translate = {0:"East",1:"South",2:"West",3:"North"}
is_riichi_translate={0:"No",1:"Yes"}

In [13]:
df['token_id'] = df['token_id'].astype(int)

In [14]:
def display_discards(discard_df):
    print(f'Hand number: {discard_df['orig_index'][0]}')

    wind = discard_df['token_id'][0] - 34
    
    print(f'Wind: {wind}, {round(discard_df['attribution_score'][0],4)}')

    seat = discard_df['token_id'][1] - 38
    
    print(f'Seat: {seat}, {round(discard_df['attribution_score'][1],4)}')
    
    is_riichi = discard_df['token_id'][2] - 44
    
    print(f'Is riichi: {is_riichi_translate[is_riichi]}, {round(discard_df['attribution_score'][2],4)}')

    dora_ind = discard_df['token_id'][3] - 46
    
    print(f'Dora Indicator: {mahjong_tiles[dora_ind]}, {round(discard_df['attribution_score'][3],4)}')
    
    for i, r in discard_df[4:].iterrows():
        print(f'{mahjong_tiles[int(r['token_id'])]}, {round(r['attribution_score'],4)}')
    print('---------------------------------------------')

In [15]:
def display_discards_no_grad(discard_df):
    print(f'Hand number: {discard_df['orig_index'][0]}')

    wind = discard_df['token_id'][0] - 34
    
    print(f'Wind: {wind}')

    seat = discard_df['token_id'][1] - 38
    
    print(f'Seat: {seat}')
    
    is_riichi = discard_df['token_id'][2] - 44
    
    print(f'Is riichi: {is_riichi_translate[is_riichi]}')

    dora_ind = discard_df['token_id'][3] - 46
    
    print(f'Dora Indicator: {mahjong_tiles[dora_ind]}')
    
    for i, r in discard_df[4:].iterrows():
        print(f'{mahjong_tiles[int(r['token_id'])]}')
    print('---------------------------------------------')

In [24]:
for hand in top_25:
    display_discards(df.loc[df['orig_index'] == hand].copy().reset_index())

Hand number: 196822
Wind: 0, -0.1048
Seat: 0, 0.117
Is riichi: No, -0.1903
Dora Indicator: East, -0.0154
1s, 0.0423
9m, -0.3434
9s, -0.0546
4m, 0.4869
East, -0.1821
1p, 0.0766
1p, -0.0177
7s, 0.1585
5p, 0.2251
4s, -0.0087
6s, 0.273
8m, -0.0122
5p, 0.2739
8s, -0.0457
6m, 0.371
East, -0.1838
7m, 0.0205
---------------------------------------------
Hand number: 178489
Wind: 0, -0.1165
Seat: 1, 0.0571
Is riichi: No, -0.1406
Dora Indicator: 9m, 0.0297
West, -0.158
8p, 0.0773
4m, 0.2608
6m, 0.6417
4m, 0.1858
East, -0.1442
East, -0.1141
4p, 0.1301
8m, 0.021
5s, -0.0387
5s, 0.0651
7p, 0.0034
5m, 0.139
4m, 0.2272
4s, 0.1465
---------------------------------------------
Hand number: 30999
Wind: 1, 0.2519
Seat: 0, 0.1544
Is riichi: No, -0.2574
Dora Indicator: 1p, 0.0999
1s, 0.0262
Red, -0.2333
South, -0.0528
3p, 0.4596
South, -0.1548
7p, 0.2466
1p, -0.0368
9s, -0.1554
Green, -0.0779
White, -0.0614
3m, 0.168
6s, 0.1013
3m, 0.2255
4m, 0.3087
7m, 0.0347
---------------------------------------------
Hand number: 123130
Wind: 1, 0.1671
Seat: 3, 0.089
Is riichi: No, -0.152
Dora Indicator: White, 0.144
West, -0.2423
2p, -0.1406
6s, 0.2551
7p, 0.2732
9s, -0.1348
5p, 0.4909
7s, 0.1372
7s, 0.0981
1s, 0.0378
8p, 0.1279
North, -0.0615
8m, -0.02
5p, 0.3201
7m, -0.0494
5m, 0.1963
---------------------------------------------
Hand number: 87929
Wind: 0, -0.0873
Seat: 3, 0.1156
Is riichi: Yes, 0.1597
Dora Indicator: 2s, -0.0198
8s, -0.0132
9s, -0.0545
5m, 0.2359
6s, 0.2286
5p, 0.2125
9m, -0.1126
4m, 0.3573
South, -0.0833
North, -0.0643
8p, 0.1639
White, -0.0724
3p, 0.1931
6p, 0.0402
2s, -0.0832
4m, 0.3184
---------------------------------------------
Hand number: 868
Wind: 0, -0.1449
Seat: 1, -0.0074
Is riichi: No, -0.2661
Dora Indicator: 6m, 0.123
South, -0.1762
8m, -0.0033
East, -0.1837
3p, 0.5571
9p, -0.0811
Green, 0.0791
8p, 0.1611
8p, 0.1075
6s, 0.277
1p, -0.0868
8m, 0.0053
West, -0.244
2p, -0.1641
8p, 0.1808
3m, 0.287
1s, 0.0547
---------------------------------------------
Hand number: 137871
Wind: 0, -0.1143
Seat: 2, -0.0081
Is riichi: No, -0.2058
Dora Indicator: 2p, 0.1008
9p, -0.0359
9s, -0.0528
9p, -0.0107
2p, -0.3631
9p, -0.0146
1s, 0.1217
6p, 0.1116
1p, -0.0281
5p, 0.2397
4m, 0.4346
5p, 0.2496
1m, 0.0
6m, 0.5583
2m, -0.1612
3m, 0.2401
---------------------------------------------
Hand number: 53527
Wind: 1, 0.1778
Seat: 3, 0.1003
Is riichi: No, -0.1883
Dora Indicator: 8s, -0.0381
East, -0.2146
1p, 0.0241
2m, -0.1831
3p, 0.353
9m, -0.205
5p, 0.453
7p, 0.2382
4m, 0.109
South, -0.1593
1s, -0.0063
West, -0.3686
Green, -0.0063
7p, 0.2174
8m, -0.0035
Red, -0.1492
3p, 0.1744
---------------------------------------------
Hand number: 53887
Wind: 0, -0.1195
Seat: 1, 0.0299
Is riichi: No, -0.2397
Dora Indicator: 8p, 0.1306
Green, 0.0243
North, -0.0163
West, -0.221
East, -0.2778
8m, 0.0042
3p, 0.3108
8s, -0.0058
5m, 0.1973
East, -0.1691
6m, 0.2787
South, -0.0547
9m, -0.1576
4m, 0.4671
3p, 0.1797
Green, 0.1035
1m, 0.0
8s, 0.0078
1m, 0.0
---------------------------------------------
Hand number: 183239
Wind: 0, -0.1272
Seat: 0, 0.1283
Is riichi: No, -0.2371
Dora Indicator: Red, -0.1339
North, -0.0104
1p, -0.0509
9s, -0.1205
8s, -0.25
8p, 0.0893
3m, 0.3793
1m, 0.0
4s, 0.0997
4p, 0.1604
8p, 0.1103
8s, -0.0831
8m, -0.0126
4m, 0.4753
8m, 0.0113
White, -0.0058
Red, -0.4391
6m, 0.4157
---------------------------------------------
Hand number: 28782
Wind: 1, 0.1597
Seat: 0, 0.1142
Is riichi: No, -0.1911
Dora Indicator: North, -0.0489
9s, -0.1781
1s, 0.0368
North, -0.0104
3p, 0.3613
3s, -0.0596
2p, -0.0719
4p, 0.1783
4p, 0.1081
4p, 0.1119
3p, 0.1261
3s, 0.0052
2s, -0.0172
5p, 0.3228
1p, -0.0492
6s, 0.2332
---------------------------------------------
Hand number: 16758
Wind: 0, -0.1465
Seat: 1, 0.036
Is riichi: No, -0.2287
Dora Indicator: 9p, 0.1321
4p, 0.0812
7p, 0.3437
6p, 0.2215
4m, 0.6919
3m, 0.1711
3s, -0.1163
South, -0.0604
White, -0.0414
Green, 0.018
East, -0.2965
8p, 0.1066
2m, -0.1606
1m, 0.0
West, -0.1746
2s, -0.0152
3s, -0.0276
Red, -0.1867
---------------------------------------------
Hand number: 188301
Wind: 0, -0.1303
Seat: 0, 0.1809
Is riichi: No, -0.3094
Dora Indicator: 2p, 0.1154
Red, -0.1671
West, -0.2057
1m, 0.0
7m, -0.0869
Green, 0.0324
9s, -0.1205
5p, 0.4243
West, -0.2255
3m, 0.2476
2p, -0.1698
9p, -0.0044
4m, 0.442
2m, -0.1906
8m, -0.0096
8m, 0.0387
8p, 0.0455
6m, 0.4762
5s, 0.0083
---------------------------------------------
Hand number: 143301
Wind: 0, -0.178
Seat: 1, 0.0006
Is riichi: Yes, 0.1685
Dora Indicator: 1m, 0.0448
West, -0.2152
South, -0.0701
South, 0.008
6p, -0.4078
Green, 0.0559
7p, 0.3854
7p, 0.2937
4s, 0.0851
6m, 0.4123
9s, -0.1605
1s, 0.0238
North, 0.0169
1m, 0.0
White, -0.0234
7m, -0.013
4p, 0.124
---------------------------------------------
Hand number: 150504
Wind: 0, -0.1331
Seat: 3, 0.0788
Is riichi: No, -0.2094
Dora Indicator: 5m, 0.1362
1s, 0.0302
East, -0.1359
North, 0.0009
1m, 0.0
9m, -0.1904
8m, 0.0
3p, 0.2696
8m, -0.0661
7p, 0.1669
1p, -0.1005
8s, -0.0983
Red, -0.1714
1m, 0.0
3m, 0.2414
3m, 0.2413
3s, -0.0676
7m, 0.0077
6s, 0.2696
---------------------------------------------
Hand number: 81900
Wind: 1, 0.3347
Seat: 2, 0.0542
Is riichi: Yes, 0.1789
Dora Indicator: 4s, -0.0924
East, -0.2032
North, -0.0137
2s, -0.0971
1p, -0.3166
3m, 0.1395
1m, 0.0
North, 0.0321
8p, 0.107
3s, -0.1245
7s, 0.0743
7s, 0.043
4p, 0.0313
7s, 0.1221
8s, -0.0518
6s, 0.2216
3p, 0.1673
---------------------------------------------
Hand number: 82771
Wind: 0, -0.1183
Seat: 1, 0.038
Is riichi: No, -0.1652
Dora Indicator: 7m, 0.0956
6m, 0.5804
1p, -0.0321
3p, 0.2983
2p, -0.3213
3m, 0.1785
2p, -0.021
4m, 0.5251
3s, -0.0591
6p, 0.088
9m, -0.2577
Green, 0.0169
South, -0.0308
3s, -0.0559
9p, -0.0756
5p, 0.3746
---------------------------------------------
Hand number: 105366
Wind: 1, 0.2408
Seat: 2, 0.0485
Is riichi: No, -0.2183
Dora Indicator: 5p, 0.0212
8p, 0.149
South, -0.0689
3p, 0.2941
Green, 0.1372
2p, -0.123
9p, -0.0574
7p, 0.2422
4p, 0.0765
1s, 0.0216
4p, 0.0732
9s, -0.0885
9s, -0.1133
1s, 0.0362
9m, -0.1598
9m, -0.0558
1m, 0.0
North, -0.0165
5s, 0.0078
8p, 0.1306
---------------------------------------------
Hand number: 97128
Wind: 1, 0.3236
Seat: 0, 0.1186
Is riichi: No, -0.1899
Dora Indicator: West, 0.122
9p, -0.0908
White, -0.0027
1p, 0.0174
1p, -0.3499
9s, -0.1237
3m, 0.4482
4p, 0.167
9s, -0.1141
2p, -0.2819
7p, 0.2336
7p, 0.0935
9s, -0.1422
2s, 0.0117
2s, -0.0657
6p, 0.0957
6p, 0.0423
---------------------------------------------
Hand number: 147181
Wind: 1, 0.1798
Seat: 2, 0.0834
Is riichi: No, -0.1394
Dora Indicator: 2m, -0.038
East, -0.1709
West, -0.2279
9s, -0.0408
3p, 0.3159
8s, -0.0228
4m, 0.3602
9s, -0.0627
North, -0.0302
7m, 0.0107
5m, 0.084
5m, 0.1643
3p, 0.1313
6p, 0.0435
Green, -0.0304
White, 0.0776
7s, 0.0711
---------------------------------------------
Hand number: 48299
Wind: 1, 0.2174
Seat: 1, 0.0632
Is riichi: No, -0.2117
Dora Indicator: 9s, -0.0635
1p, 0.0216
9m, -0.1517
4m, 0.3443
East, -0.3148
Green, 0.0371
9m, -0.1309
3s, -0.0488
6p, -0.0367
Green, 0.0176
8p, 0.1216
2p, -0.067
5p, 0.212
West, -0.2411
3m, 0.1608
3m, 0.2272
9m, -0.1939
8p, 0.1062
5s, 0.0306
---------------------------------------------
Hand number: 25127
Wind: 0, -0.1146
Seat: 2, 0.0241
Is riichi: No, -0.1694
Dora Indicator: West, 0.2037
West, -0.2584
9s, -0.065
South, -0.0251
9m, -0.6002
6m, 0.4139
6p, 0.1001
6p, 0.1368
7p, 0.2495
4p, 0.2064
3p, 0.2429
2p, -0.104
1p, -0.0448
5p, 0.7266
9m, -0.2454
---------------------------------------------
Hand number: 142408
Wind: 0, -0.1502
Seat: 2, 0.0193
Is riichi: No, -0.2217
Dora Indicator: 9p, 0.1017
2p, -0.0691
Green, 0.0407
7p, 0.2592
Red, -0.6598
White, 0.0303
6s, 0.2988
5s, -0.0114
3m, 0.262
3p, 0.2847
5p, 0.5313
7s, 0.0687
3p, 0.2276
8p, 0.1459
---------------------------------------------
Hand number: 195246
Wind: 0, -0.1206
Seat: 0, 0.1363
Is riichi: No, -0.1965
Dora Indicator: South, 0.0886
1m, 0.0
1s, 0.0347
1s, 0.0524
9s, -0.3766
1p, -0.0348
3p, 0.3975
4p, 0.1691
6p, -0.0095
9m, -0.1709
6s, 0.1474
5m, 0.1649
4s, 0.0017
9p, -0.077
6s, 0.1199
Green, 0.0429
1p, -0.1006
2m, -0.317
---------------------------------------------
Hand number: 22714
Wind: 0, -0.0792
Seat: 0, 0.1458
Is riichi: No, -0.1003
Dora Indicator: 1s, 0.2022
1p, 0.0293
East, -0.0836
Red, -0.1198
7s, 0.2235
5p, 0.1841
6p, 0.1058
5p, 0.3295
6s, 0.2262
4p, 0.1278
3s, -0.0706
9m, -0.1015
5p, 0.1663
3m, 0.1932
---------------------------------------------
Hand number: 132598
Wind: 1, 0.2434
Seat: 3, 0.1668
Is riichi: No, -0.198
Dora Indicator: 2s, -0.0194
West, -0.1943
North, -0.0255
8m, 0.0219
4p, 0.0548
8m, -0.0198
3p, 0.3879
North, -0.0007
South, -0.0566
5s, 0.0424
Green, -0.019
5s, -0.0259
6m, 0.4871
3s, -0.073
4s, -0.0414
2m, -0.1498
---------------------------------------------
Hand number: 165568
Wind: 0, -0.1222
Seat: 3, 0.1448
Is riichi: No, -0.2235
Dora Indicator: 7p, 0.1989
White, -0.0734
Green, 0.0148
1p, -0.0218
East, -0.3533
7m, -0.0034
6m, 0.8411
8s, 0.0121
9p, -0.2052
South, -0.1069
3m, 0.241
3s, -0.0239
8s, -0.1014
1s, 0.0396
9m, -0.2323
7p, 0.2565
White, -0.0687
---------------------------------------------
Hand number: 191050
Wind: 1, 0.2428
Seat: 1, 0.1106
Is riichi: No, -0.1046
Dora Indicator: 1s, 0.1919
9m, -0.129
Green, 0.0404
3s, -0.0269
4p, 0.052
6m, 0.3273
6s, 0.287
6m, 0.4495
7s, 0.1673
4m, 0.2639
9p, -0.1245
6p, 0.1004
West, -0.2169
---------------------------------------------
Hand number: 116879
Wind: 0, -0.1013
Seat: 1, 0.0656
Is riichi: No, -0.1211
Dora Indicator: 3p, 0.0441
Green, -0.0658
Red, -0.1485
3p, 0.3397
3p, 0.4385
3m, 0.1266
3m, 0.3673
6s, 0.2682
8m, 0.0303
6m, 0.322
4s, -0.0067
5p, 0.2418
---------------------------------------------
Hand number: 66892
Wind: 1, 0.2146
Seat: 1, 0.0457
Is riichi: Yes, 0.1317
Dora Indicator: Red, -0.0873
North, -0.0443
1m, 0.0
3m, 0.2645
Green, 0.0948
3m, 0.1217
2s, 0.0254
8m, 0.0113
9p, -0.022
Red, -0.2263
4p, 0.0625
4s, 0.0774
3m, 0.1416
7s, 0.0994
7p, 0.0983
3p, 0.2431
---------------------------------------------

In [ ]:
for hand in top_25:
    display(df.loc[df['orig_index'] == hand].copy().reset_index())